version: '3.2'
services:
  sql-dumper:
    build:
      context: .
      dockerfile: ./sql-dumper/Dockerfile
    volumes:
      - ./sql-dumper/init_db.sh:/scripts/init_db.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
  keycloak:
    image: uselagoon/keycloak
    user: '111111111'
    ports:
      - '8088:8080'
    networks:
      - default
  keycloak-db:
    image: uselagoon/keycloak-db
    labels:
      lagoon.type: none
    ports:
      - '3336:3306'
    networks:
      - default